# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'back_wheel_test_individual.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow

import gol
import serial
import time
import struct

class Ui_MainWindow(object):
    def __init__(self,parent=None) -> None:
        super(Ui_MainWindow,self).__init__()
        gol._init()
        self.ser = serial.Serial(
            port='/dev/ttyUSB0',
            baudrate=115200,
            
        )
        self.ser.timeout = 0.5

        self.thread_read = None
        self.thread_send = None
        self.thread_show = None
        self.send_buffer = bytearray([00,00,00,00,00,00,00,00])
        self.t = 0

        # hub no: 0: both 1:left 2: right, default:0
        # steer no: 0: both 1:left 2: right, default:0
        gol.set_value('hub_no',0)
        gol.set_value('steer_no',0)

        gol.set_value('fname',time.strftime("%m%d%H%M")+'.txt')
        self.mainwindow = QMainWindow()
        self.setupUi(self.mainwindow)

        self.hub_default_buffer = bytearray([0x04]) + struct.pack('f',20.0)
        self.steer_default_buffer = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 240, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 240, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 240, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 220, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 220, 91, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 310, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 310, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 290, 91, 17))
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 180, 421, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(160, 380, 421, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 60, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 60, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(160, 40, 91, 17))
        self.label_6.setObjectName("label_6")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(160, 490, 421, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 560, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(440, 560, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 540, 91, 17))
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 630, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(320, 540, 91, 17))
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 560, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 610, 91, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(300, 630, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 240, 89, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 310, 89, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 220, 131, 151))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(220, 20, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(750, 20, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(890, 370, 113, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 440, 89, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(770, 420, 91, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(750, 440, 113, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(630, 370, 89, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(930, 350, 91, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(770, 350, 91, 17))
        self.label_15.setObjectName("label_15")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(620, 310, 421, 231))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 190, 113, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(150, 170, 91, 17))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(20, 190, 91, 17))
        self.label_25.setObjectName("label_25")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(750, 370, 113, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(620, 570, 421, 91))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.setGeometry(QtCore.QRect(190, 10, 221, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 50, 221, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(620, 180, 421, 41))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setGeometry(QtCore.QRect(20, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_13.setGeometry(QtCore.QRect(180, 10, 89, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(620, 230, 421, 71))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(20, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 40, 89, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_22 = QtWidgets.QLabel(self.frame_8)
        self.label_22.setGeometry(QtCore.QRect(160, 20, 91, 17))
        self.label_22.setObjectName("label_22")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 40, 151, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setGeometry(QtCore.QRect(300, 20, 91, 17))
        self.label_24.setObjectName("label_24")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_14.setGeometry(QtCore.QRect(290, 40, 113, 25))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(160, 70, 421, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox = QtWidgets.QComboBox(self.frame_9)
        self.comboBox.setGeometry(QtCore.QRect(120, 54, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(620, 70, 421, 91))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(10, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 50, 141, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.frame_5.raise_()
        self.frame_4.raise_()
        self.frame.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_3.raise_()
        self.label_3.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_6.raise_()
        self.label_9.raise_()
        self.pushButton_5.raise_()
        self.label_10.raise_()
        self.lineEdit_5.raise_()
        self.label_8.raise_()
        self.lineEdit_7.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit_8.raise_()
        self.pushButton_8.raise_()
        self.label_13.raise_()
        self.lineEdit_9.raise_()
        self.pushButton_9.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.lineEdit_10.raise_()
        self.frame_6.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.frame_9.raise_()
        self.frame_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.click_event()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sine"))
        self.label.setText(_translate("MainWindow", "Amplitude"))
        self.label_2.setText(_translate("MainWindow", "Freq."))
        self.pushButton_2.setText(_translate("MainWindow", "Step"))
        self.label_3.setText(_translate("MainWindow", "Amplitude"))
        self.label_4.setText(_translate("MainWindow", "Speed Control (rad/s)"))
        self.label_5.setText(_translate("MainWindow", "Brake"))
        self.pushButton_3.setText(_translate("MainWindow", "Brake"))
        self.label_6.setText(_translate("MainWindow", "Current"))
        self.label_7.setText(_translate("MainWindow", "Position Control (rad)"))
        self.pushButton_4.setText(_translate("MainWindow", "Sine"))
        self.label_9.setText(_translate("MainWindow", "Freq."))
        self.pushButton_5.setText(_translate("MainWindow", "Step"))
        self.label_10.setText(_translate("MainWindow", "Amplitude"))
        self.label_8.setText(_translate("MainWindow", "Amplitude"))
        self.pushButton_6.setText(_translate("MainWindow", "Start"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.label_11.setText(_translate("MainWindow", "HUB CONTROL PANEL"))
        self.label_12.setText(_translate("MainWindow", "STEER CONTROL PANEL"))
        self.pushButton_8.setText(_translate("MainWindow", "Step"))
        self.label_13.setText(_translate("MainWindow", "Amplitude"))
        self.pushButton_9.setText(_translate("MainWindow", "Sine"))
        self.label_14.setText(_translate("MainWindow", "Freq."))
        self.label_15.setText(_translate("MainWindow", "Amplitude"))
        self.label_16.setText(_translate("MainWindow", "POS Abs Control (rad/s)"))
        self.label_23.setText(_translate("MainWindow", "Amplitude"))
        self.label_25.setText(_translate("MainWindow", "max speed"))
        self.label_19.setText(_translate("MainWindow", "Brake"))
        self.pushButton_11.setText(_translate("MainWindow", "Brake LOCK"))
        self.pushButton_12.setText(_translate("MainWindow", "Brake RELEASE"))
        self.label_20.setText(_translate("MainWindow", "Initialize"))
        self.pushButton_13.setText(_translate("MainWindow", "INIT"))
        self.label_21.setText(_translate("MainWindow", "POS Rel Control"))
        self.pushButton_14.setText(_translate("MainWindow", "Start"))
        self.label_22.setText(_translate("MainWindow", "Angle/deg"))
        self.label_24.setText(_translate("MainWindow", "max speed"))
        self.label_18.setText(_translate("MainWindow", "Wheel Selection"))
        self.comboBox.setItemText(0, _translate("MainWindow", "-- please select --"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Both"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Left"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Right"))
        self.label_26.setText(_translate("MainWindow", "Wheel Selection"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "-- please select --"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Both"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Left"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Right"))

        # add on
        self.lineEdit.setText(_translate("MainWindow", "4000"))
        self.lineEdit_2.setText(_translate("MainWindow", "10"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.lineEdit_4.setText(_translate("MainWindow", "20"))
        self.lineEdit_5.setText(_translate("MainWindow", "10"))
        self.lineEdit_6.setText(_translate("MainWindow", "10"))
        self.lineEdit_7.setText(_translate("MainWindow", "10"))
        self.lineEdit_12.setText(_translate("MainWindow", "1000"))
        self.lineEdit_10.setText(_translate("MainWindow", "1000"))
        self.lineEdit_8.setText(_translate("MainWindow", "0.2"))
        self.lineEdit_9.setText(_translate("MainWindow", "1000"))
        self.lineEdit_14.setText(_translate("MainWindow", "500"))
        self.lineEdit_13.setText(_translate("MainWindow", "500"))

    def click_event(self):
        self.pushButton_6.clicked.connect(self.serialState)
        self.pushButton.clicked.connect(self.vel_sin_gen)
        self.pushButton_2.clicked.connect(self.vel_step_gen)
        self.pushButton_3.clicked.connect(self.brake)
        self.pushButton_4.clicked.connect(self.pos_sin_gen)
        self.pushButton_5.clicked.connect(self.pos_step_gen)
        self.pushButton_7.clicked.connect(self.closeEvent)
        self.pushButton_13.clicked.connect(self.steer_pos_init)
        self.pushButton_9.clicked.connect(self.steer_pos_sin)
        self.pushButton_8.clicked.connect(self.steer_pos_step)
        self.pushButton_11.clicked.connect(self.steer_brake_lock)
        self.pushButton_12.clicked.connect(self.steer_brake_release)
        self.pushButton_14.clicked.connect(self.steer_pos_rel)
        self.comboBox.currentTextChanged.connect(self.hub_wheel_select)
        self.comboBox_2.currentTextChanged.connect(self.steer_wheel_select)

    def hub_wheel_select(self):
        hub_no = self.comboBox.currentText()
        steer_no = gol.get_value('steer_no')
        if hub_no != '-- please select --':
            if hub_no == 'Both':
                gol.set_value('hub_no',0)
            elif hub_no == 'Left':
                gol.set_value('hub_no',1)
            elif hub_no == 'Right':
                gol.set_value('hub_no',2)
        print('hub_no: ', hub_no, 'steer_no',steer_no)
    
    def steer_wheel_select(self):
        steer_no = self.comboBox_2.currentText()
        hub_no = gol.get_value('hub_no')
        if steer_no != '-- please select --':
            if steer_no == 'Both':
                gol.set_value('steer_no',0)
            elif steer_no == 'Left':
                gol.set_value('steer_no',1)
            elif steer_no == 'Right':
                gol.set_value('steer_no',2)
        print('hub_no: ', hub_no, 'steer_no',steer_no)
        
    def serialState(self):
        pass


    def vel_sin_gen(self):
      
        self.motion = bytearray([0x02])
        self.motion_flag = 1
        hub_no = gol.get_value('hub_no')
        if hub_no == 0:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)
            
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit.text())
            gol.set_value('T_1',self.lineEdit_2.text())

            gol.set_value('amp_2',self.lineEdit.text())
            gol.set_value('T_2',self.lineEdit_2.text())

        elif hub_no == 1:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit.text())
            gol.set_value('T_1',self.lineEdit_2.text())
        elif hub_no == 2:
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_2',self.lineEdit.text())
            gol.set_value('T_2',self.lineEdit_2.text())
        
    
    def vel_step_gen(self):
        
        self.motion = bytearray([0x02])
        self.motion_flag = 2
        hub_no = gol.get_value('hub_no')
        if hub_no == 0:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)
            
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_3.text())
            gol.set_value('amp_2',self.lineEdit_3.text())
        elif hub_no == 1:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_3.text())
        elif hub_no == 2:
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_2',self.lineEdit_3.text())

    def brake(self):
        
        self.motion = bytearray([0x04])
        self.motion_flag = 3
        hub_no = gol.get_value('hub_no')
        if hub_no == 0:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)
            
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('cur_1',self.lineEdit_4.text())
            gol.set_value('cur_2',self.lineEdit_4.text())
        elif hub_no == 1:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)

            gol.set_value('cur_1',self.lineEdit_4.text())
        elif hub_no == 2:
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('cur_2',self.lineEdit_4.text())

    def pos_sin_gen(self):
       
        self.motion = bytearray([0x01])
        self.motion_flag = 4
        hub_no = gol.get_value('hub_no')
        if hub_no == 0:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)
            
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_5.text())
            gol.set_value('T_1',self.lineEdit_6.text())

            gol.set_value('amp_2',self.lineEdit_5.text())
            gol.set_value('T_2',self.lineEdit_6.text())
        elif hub_no == 1:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_5.text())
            gol.set_value('T_1',self.lineEdit_6.text())
        elif hub_no == 2:
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_2',self.lineEdit_5.text())
            gol.set_value('T_2',self.lineEdit_6.text())

    def pos_step_gen(self):
        
        self.motion = bytearray([0x01])
        self.motion_flag = 5
        hub_no = gol.get_value('hub_no')
        if hub_no == 0:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)
            
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_7.text())
            gol.set_value('amp_2',self.lineEdit_7.text())
        elif hub_no == 1:
            gol.set_value('motion_1',self.motion)
            gol.set_value('motion_flag_1',self.motion_flag)

            gol.set_value('amp_1',self.lineEdit_7.text())
        elif hub_no == 2:
            gol.set_value('motion_2',self.motion)
            gol.set_value('motion_flag_2',self.motion_flag)

            gol.set_value('amp_2',self.lineEdit_7.text())


    #steering
    def steer_pos_init(self):
        self.steer_motion = bytearray([0x01])
        self.steer_motion_flag = 1


        vel = 0
        pos = 0
        steer_send_buffer = self.steer_motion + struct.pack('H',vel) + struct.pack('i',pos)

        # get rear_send_buffer
        send_buffer_1 = gol.get_value('send_buffer_1',self.hub_default_buffer)
        send_buffer_2 = gol.get_value('send_buffer_2',self.hub_default_buffer)
        steer_send_buffer_1 = gol.get_value('steer_send_buffer_1',self.steer_default_buffer)
        steer_send_buffer_2 = gol.get_value('steer_send_buffer_2',self.steer_default_buffer)

        steer_no = gol.get_value('steer_no')

        if steer_no == 0:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = steer_send_buffer
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

        elif steer_no ==1:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)

            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)
        elif steer_no == 2:
            steer_send_buffer_1 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)
            steer_send_buffer_2 = steer_send_buffer

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)
        
        Send_buffer = send_buffer_1 + send_buffer_2 + steer_send_buffer_1 + steer_send_buffer_2
        if self.ser.is_open:
            self.ser.write(Send_buffer)
            #print('send buffer',len(Send_buffer))


    def steer_pos_rel(self):
        self.steer_motion  = bytearray([0x02])
        self.steer_motion_flag = 2
        gol.set_value('steer_motion',self.steer_motion)
        gol.set_value('steer_motion_flag',self.steer_motion_flag)
        gol.set_value('steer_max_speed',self.lineEdit_14.text())
        gol.set_value('steer_rel_pos',self.lineEdit_12.text())

        # get rear_send_buffer
        
        
        
        vel = int(self.lineEdit_14.text())
        pos = int(self.lineEdit_12.text())

        steer_send_buffer = self.steer_motion + struct.pack('H',vel) + struct.pack('i',pos)

        # get rear_send_buffer
        send_buffer_1 = gol.get_value('send_buffer_1',self.hub_default_buffer)
        send_buffer_2 = gol.get_value('send_buffer_2',self.hub_default_buffer)
        steer_send_buffer_1 = gol.get_value('steer_send_buffer_1',self.steer_default_buffer)
        steer_send_buffer_2 = gol.get_value('steer_send_buffer_2',self.steer_default_buffer)

        steer_no = gol.get_value('steer_no')


        if steer_no == 0:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = steer_send_buffer
        elif steer_no ==1:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)
        elif steer_no == 2:
            steer_send_buffer_1 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)
            steer_send_buffer_2 = steer_send_buffer
        
        Send_buffer = send_buffer_1 + send_buffer_2 + steer_send_buffer_1 + steer_send_buffer_2

        if self.ser.is_open:
            self.ser.write(Send_buffer)
            #print('send buffer',Send_buffer)

    def steer_pos_sin(self):
        self.steer_motion = bytearray([0x03])
        self.steer_motion_flag = 3
        steer_no = gol.get_value('steer_no')
        if steer_no == 0:
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)
            
            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

            gol.set_value('steer_max_speed_1',self.lineEdit_13.text())
            gol.set_value('steer_amp_1',self.lineEdit_10.text())
            gol.set_value('steer_freq_1',self.lineEdit_8.text())

            gol.set_value('steer_max_speed_2',self.lineEdit_13.text())
            gol.set_value('steer_amp_2',self.lineEdit_10.text())
            gol.set_value('steer_freq_2',self.lineEdit_8.text())

        elif steer_no == 1:
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)

            gol.set_value('steer_max_speed_1',self.lineEdit_13.text())
            gol.set_value('steer_amp_1',self.lineEdit_10.text())
            gol.set_value('steer_freq_1',self.lineEdit_8.text())
        elif steer_no == 2:
            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

            gol.set_value('steer_max_speed_2',self.lineEdit_13.text())
            gol.set_value('steer_amp_2',self.lineEdit_10.text())
            gol.set_value('steer_freq_2',self.lineEdit_8.text())

    def steer_pos_step(self):
        self.steer_motion = bytearray([0x03])
        self.steer_motion_flag = 4
        steer_no = gol.get_value('steer_no')
        if steer_no == 0:
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)
            
            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

            gol.set_value('steer_max_speed_1',self.lineEdit_13.text())
            gol.set_value('steer_amp_1',self.lineEdit_9.text())

            gol.set_value('steer_max_speed_2',self.lineEdit_13.text())
            gol.set_value('steer_amp_2',self.lineEdit_9.text())
        elif steer_no == 1:
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)

            gol.set_value('steer_max_speed_1',self.lineEdit_13.text())
            gol.set_value('steer_amp_1',self.lineEdit_9.text())
        elif steer_no == 2:
            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

            gol.set_value('steer_max_speed_2',self.lineEdit_13.text())
            gol.set_value('steer_amp_2',self.lineEdit_9.text())


    def steer_brake_lock(self):
        self.steer_motion = bytearray([0x04])
        self.steer_motion_flag = 5

        vel = 0
        pos = 0
        steer_send_buffer = self.steer_motion + struct.pack('H',vel) + struct.pack('i',pos)

        # get rear_send_buffer
        send_buffer_1 = gol.get_value('send_buffer_1',self.hub_default_buffer)
        send_buffer_2 = gol.get_value('send_buffer_2',self.hub_default_buffer)
        steer_send_buffer_1 = gol.get_value('steer_send_buffer_1',self.steer_default_buffer)
        steer_send_buffer_2 = gol.get_value('steer_send_buffer_2',self.steer_default_buffer)

        steer_no = gol.get_value('steer_no')

        if steer_no == 0:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = steer_send_buffer
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

        elif steer_no ==1:
            steer_send_buffer_1 = steer_send_buffer
            # steer_send_buffer_2 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)

            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)
        elif steer_no == 2:
            # steer_send_buffer_1 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)
            steer_send_buffer_2 = steer_send_buffer

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)
        
        Send_buffer = send_buffer_1 + send_buffer_2 + steer_send_buffer_1 + steer_send_buffer_2

        if self.ser.is_open:
            self.ser.write(Send_buffer)     
    
    def steer_brake_release(self):
        self.steer_motion = bytearray([0x05])
        self.steer_motion_flag = 6
        vel = 0
        pos = 0
        steer_send_buffer = self.steer_motion + struct.pack('H',vel) + struct.pack('i',pos)

        # get rear_send_buffer
        send_buffer_1 = gol.get_value('send_buffer_1',self.hub_default_buffer)
        send_buffer_2 = gol.get_value('send_buffer_2',self.hub_default_buffer)
        steer_send_buffer_1 = gol.get_value('steer_send_buffer_1',self.steer_default_buffer)
        steer_send_buffer_2 = gol.get_value('steer_send_buffer_2',self.steer_default_buffer)

        steer_no = gol.get_value('steer_no')

        if steer_no == 0:
            steer_send_buffer_1 = steer_send_buffer
            steer_send_buffer_2 = steer_send_buffer
            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)

        elif steer_no ==1:
            steer_send_buffer_1 = steer_send_buffer
            # steer_send_buffer_2 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)

            gol.set_value('steer_motion_1',self.steer_motion)
            gol.set_value('steer_motion_flag_1',self.steer_motion_flag)
        elif steer_no == 2:
            # steer_send_buffer_1 = bytearray([0x00]) + struct.pack('H',0) + struct.pack('i',0)
            steer_send_buffer_2 = steer_send_buffer

            gol.set_value('steer_motion_2',self.steer_motion)
            gol.set_value('steer_motion_flag_2',self.steer_motion_flag)
        
        Send_buffer = send_buffer_1 + send_buffer_2 + steer_send_buffer_1 + steer_send_buffer_2

        if self.ser.is_open:
            self.ser.write(Send_buffer)
    
    def closeEvent(self):
        pass